### PR TITLE
Version 0.2.0

### PR DESCRIPTION
**Pull request by ashwinthomson**

### CODE REVIEW

**Comment by ghost** [comment]
Navbar Problems:
Search Button:  change active to color not hover.
Link for profile pic icon also
Remove decorations of text in navbar.
No Dropdown for down arrow div.
Dropdown for search icon
Limit the size of dropdowns and make it scrollable

Cover Photo Probs:
The change in size of camera icon.
Dropdown menu of "..." Button
hovering of camera icon removes other icon
Try to align cover image with facebook icon in navbar.

 Right Pane:
Overflow for bottom pane
chat window pointer to hand.

Profile pic camera icon

Change Title.

Profile Name is not given in cover photo.

**Comment by karthikamg** [comment]
Navbar problems:
Cursor(pointer) in the dropdown for chat icon and icon for notifications.
Links in the dropdown for chat icon and icon for notifications is not complete.
Cross symbol on hover in the dropdown for user icon.

**Comment by vijay-stayntouch** [comment]
Still a lot of inline styles.. please remove them before next release.

**Comment by karthikamg** [comment]
Navbar problems:
Search icon background color & color change on hover.
'View All' link is fixed.
Cursor(pointer) in the dropdown for chat icon, icon for notifications and links in privacy shortcuts.

Update profile pic in profile pic image.

Certain class names are not specific.

**Pull request merged**
